#!/bin/sh

increase() {
    brightnessctl s +"$1"% >/dev/null
}

decrease() {
    brightnessctl s "$1"%- >/dev/null
}

get_brightness() {
    echo $(brightnessctl | grep 'Current brightness' | cut -d' ' -f4 | tr -d '()')
}

send_notification() {
    dunstify -t 1000 -h string:x-dunst-stack-tag:brightness "Brightness" $(get_brightness)
}

print_help() {
    echo "Usage: backlightctl [option] [value]"
    echo ""
    echo "Options:"
    printf "  %-20s\t%-54s\n" \
        "-h, --help" "Show this help message." \
        "-i, --increase" "Increase brightness." \
        "-d, --decrease" "Decrease brightness." \
        "-g, --get" "Get current brightness."
}


case "$#" in
    0)
        print_help
        ;;
    *)
        case "$1" in
            "-i" | "-increase")
                increase $2
                send_notification
                polybar-msg hook brightness 1
                ;;
            "-d" | "--decrease")
                decrease $2
                send_notification
                polybar-msg hook brightness 1
                ;;
            "-g" | "--get")
                echo $(get_brightness)
                ;;
            "-h" | "--help")
                print_help
                ;;
        esac
esac
