#!/usr/bin/env sh

reset=$(tput sgr0)
bold=$(tput bold)

accent="$(tput setaf 4)"
accent2="$(tput setaf 5)"
normal="$(tput setaf 7)"

get_art() {
    echo "${bold}${accent}      /\\
     /  \\
    /\\   \\
${normal}   / > ω <\\
  /   ,,   \\
 /   |  |  -\\
/_-''    ''-_\\${reset}"
}

[ "${1}" = "art" ] && echo "$(get_art)" && exit 0

print() {
    [ -z "${2}" ] || printf "${bold}${accent}%-8s${reset} ${normal}%s\n" "${1:-NULL}" "${2}"
}

user_info="${bold}${accent2}$(whoami)${normal}@${accent2}$(hostname)${reset}"
uptime="$(uptime | awk '{print $3}' | sed -e 's/,//g' -e 's/\:/h /g')m"
pkgs="$(pacman -Q | wc -l)"
shell="${SHELL##*/}"
wm="${DESKTOP_SESSION}"

echo "${user_info}"
print "os" "nyarch linux"
print "uptime" "${uptime}"
print "pkgs" "${pkgs}"
print "terminal" "alacritty"
print "shell" "${shell}"
print "wm" "${wm}"
