dpi-aware=no
icon-theme=Papirus-Dark
width=48
font=Jetbrains Mono:size=11
# line-height=50
# fields=name,generic,comment,categories,filename,keywords
terminal=ghostty -e
prompt=""
placeholder="Search for apps..."
show-actions=yes
match-counter=yes
minimal-lines=yes
exit-on-keyboard-focus-loss=yes

horizontal-pad=20
vertical-pad=16
inner-pad=20

[colors]
background=191724ff
text=e0def4ff
match=ebbcbaff
selection=6e6a8626
selection-text=e0def4ff
selection-match=ebbcbaff
border=6e6a8633
prompt=e0def4ff
placeholder=6e6a86ff
input=e0def4ff
counter=6e6a86ff

[border]
radius=6
selection-radius=2
