#! /bin/sh
### RULES ###
bspc rule -r *

bspc rule -a discord desktop='10' follow=off

### MONITORS ###

if [[ $(hostname) = "archdesktop" ]]; then
    xrandr --output DP-2 --primary --mode 1920x1080 --rate 144.00 --rotate normal --output HDMI-0 --mode 1920x1080 --rate 60.00 --rotate normal --right-of DP-2  --output DP-1 --mode 1920x1080 --rate 60.00 --rotate normal --left-of DP-2
   
    feh --bg-scale $HOME/Downloads/wallhaven-z8dg9y.png
 
    bspc monitor DP-4 -d 1 2 3 4 5 6
    bspc monitor DP-1 -d 7 8
    bpsc monitor HDMI-0 -d 9 10
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi


bspc config top_padding             27
bspc config bottom_padding          0
bspc config left_padding            0
bspc config right_padding           0
bspc config border_width            2
bspc config window_gap              8

bspc config split_ratio             0.52
bspc config presel_feedback         false
bspc config ignore_ewmh_focus       true

feh --bg-scale $HOME/Pictures/wallhaven-g7wog3.png

### COLORS ###
bspc config normal_border_color $(xresget background)
bspc config active_border_color $(xresget color3)
bspc config focused_border_color $(xresget color8)
bspc config presel_feedback_color $(xresget color1)


### AUTOSTART ###
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x fcitx > /dev/null || fcitx &
pgrep -x picom > /dev/null || picom --experimental-backends &

killall dunst
dunst &

killall flameshot
flameshot &

killall blueman-applet
blueman-applet &

$HOME/.config/polybar/launch.sh

bspwm_handle_urgency &

pgrep -x Discord > /dev/null || discord &

