#! /bin/sh
### RULES ###
bspc rule -r *

bspc rule -a discord desktop='^10' follow=off


### MONITORS ###
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config top_padding             27
bspc config bottom_padding          0
bspc config left_padding            0
bspc config right_padding           0
bspc config border_width            2
bspc config window_gap              8

bspc config split_ratio             0.52

bspc config ignore_ewmh_focus true

feh --bg-scale $HOME/Pictures/wallhaven-g7wog3.png

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color0"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color8"
bspc config presel_feedback_color "$color1"


### AUTOSTART ###
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x Discord > /dev/null || discord &

killall "picom"
picom --experimental-backends &

killall "dunst"
dunst &

killall "flameshot"
flameshot &

killall "blueman-applet"
blueman-applet &

$HOME/.config/polybar/launch.sh


bspwm_handle_urgency &

