format = """\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
[>](red) """
add_newline = false

[username]
disabled = false

[directory]
style = "yellow"

[git_branch]
symbol = ""

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"
