set -g prefix C-a
unbind C-b
bind C-a send-prefix

unbind R
bind R source-file ~/.config/tmux/tmux.conf \; display 'Sourced ~/.config/tmux/tmux.conf!'

set-option -g extended-keys on
set -as terminal-features 'alacritty*:extkeys'

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

bind S command-prompt -p "Shift to index:" "run-shell 'tmux-shift %1'"
bind f run-shell "tmux-session-manager"

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Undercurl support
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

set -g status-right ""
set -g status-left ""
setw -g window-status-format " #I: #W "
setw -g window-status-current-format "#[bg=#26233a] #I: #W #[default]"

set -g status-fg white
set -g status-style bg=default

set -g mouse on

set -s escape-time 0

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

set -g renumber-windows on

set -g display-time 4000
set -g status-interval 5

