[[profile]]
name = "Home Desktop"

[[profile.output]]
enable = true
search = "m=KG251Q"
mode = "preferred"
position = "2560,320"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = true
search = "m=XG27ACDNG"
mode = "2560x1440@180"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = true
search = "m=T24B350"
mode = "preferred"
position = "-1920,400"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile]]
name = "Home Desktop Dual"

[[profile.output]]
enable = true
search = "m=XG27ACDNG"
mode = "2560x1440@360"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = true
search = "m=T24B350"
mode = "preferred"
position = "-1920,400"
scale = 1.0
transform = "normal"
adaptive_sync = false
